name: deploy
on: 
 - push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build 
        run: |
            ls -la 
            yarn install
            yarn build

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hostsa

      - name: Deploy with rsync
        run: | 
          TARGET_DIR="/var/www/html/${{ steps.package-version.outputs.current-version}}"
          rsync -a --rsync-path="mkdir -p $TARGET_DIR && rsync" ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$TARGET_DIR

      - name: Update symlink 
        run: | 
          sudo rm -f /var/www/html/latest
          sudo ln -sf /var/www/html/${{ steps.package-version.outputs.current-version}} /var/www/html/latest
